name: 'Zigbee Contact (Add Hej)'
packageKey: 'zigbee-contact-v2-add-hej'
description: 'source: https://github.com/byjjoon/SmartThingsEdgeDrivers/tree/J/drivers/SmartThings/zigbee-contact'
permissions:
  zigbee: {}
