name: 'Zigbee Motion Sensor (Add Hej)'
packageKey: 'st-zigbee-motion-sensor-add-hej'
description: 'just add fingerprint. (source : https://github.com/byjjoon/SmartThingsEdgeDrivers/tree/J/drivers/SmartThings/zigbee-motion-sensor)'
permissions:
  zigbee: {}
